/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizza360;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author SasGyula(SZOFT_2023_
 */
public class pizzaGUI extends javax.swing.JFrame {

    /**
     * Creates new form pizzaGUI
     */
    public pizzaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbgPizzafelek = new javax.swing.ButtonGroup();
        lblPizza = new javax.swing.JLabel();
        pnlPizzafelek = new javax.swing.JPanel();
        cmbPizzafelek = new javax.swing.JComboBox<>();
        pnlFeltetek = new javax.swing.JPanel();
        cbxSajt = new javax.swing.JCheckBox();
        cbxJapanejo = new javax.swing.JCheckBox();
        cbxAnanasz = new javax.swing.JCheckBox();
        cbxSzalami = new javax.swing.JCheckBox();
        spnSajt = new javax.swing.JSpinner();
        spnJalapenjo = new javax.swing.JSpinner();
        spnAnanasz = new javax.swing.JSpinner();
        spnSzalami = new javax.swing.JSpinner();
        pnlMeret = new javax.swing.JPanel();
        cmbMeret = new javax.swing.JComboBox<>();
        btnRendeles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizza 360");
        setResizable(false);
        setSize(new java.awt.Dimension(500, 300));

        lblPizza.setText("<html><b style = \"font-size:30\">Pizza 360</b></html>");
        lblPizza.setToolTipText("");

        pnlPizzafelek.setBorder(javax.swing.BorderFactory.createTitledBorder("Pizzafélék"));

        cmbPizzafelek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pizza kiválasztása", "Margherita", "Hawaii", "Sonkás", "Magyaros" }));
        cmbPizzafelek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPizzafelekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPizzafelekLayout = new javax.swing.GroupLayout(pnlPizzafelek);
        pnlPizzafelek.setLayout(pnlPizzafelekLayout);
        pnlPizzafelekLayout.setHorizontalGroup(
            pnlPizzafelekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPizzafelekLayout.createSequentialGroup()
                .addComponent(cmbPizzafelek, 0, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPizzafelekLayout.setVerticalGroup(
            pnlPizzafelekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPizzafelekLayout.createSequentialGroup()
                .addComponent(cmbPizzafelek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pnlFeltetek.setBorder(javax.swing.BorderFactory.createTitledBorder("Plusz feltétek"));

        cbxSajt.setText("Sajt");
        cbxSajt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSajtItemStateChanged(evt);
            }
        });

        cbxJapanejo.setText("Jalapenjo");
        cbxJapanejo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxJapanejoItemStateChanged(evt);
            }
        });
        cbxJapanejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxJapanejoActionPerformed(evt);
            }
        });

        cbxAnanasz.setText("Ananász");
        cbxAnanasz.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAnanaszItemStateChanged(evt);
            }
        });

        cbxSzalami.setText("Szalámi");
        cbxSzalami.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSzalamiItemStateChanged(evt);
            }
        });

        spnSajt.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        spnSajt.setEnabled(false);

        spnJalapenjo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        spnJalapenjo.setEnabled(false);

        spnAnanasz.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        spnAnanasz.setEnabled(false);

        spnSzalami.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        spnSzalami.setEnabled(false);

        javax.swing.GroupLayout pnlFeltetekLayout = new javax.swing.GroupLayout(pnlFeltetek);
        pnlFeltetek.setLayout(pnlFeltetekLayout);
        pnlFeltetekLayout.setHorizontalGroup(
            pnlFeltetekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFeltetekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFeltetekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxJapanejo)
                    .addComponent(cbxAnanasz)
                    .addComponent(cbxSzalami)
                    .addComponent(cbxSajt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFeltetekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnSajt)
                    .addComponent(spnSzalami)
                    .addComponent(spnAnanasz)
                    .addComponent(spnJalapenjo)))
        );
        pnlFeltetekLayout.setVerticalGroup(
            pnlFeltetekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFeltetekLayout.createSequentialGroup()
                .addGroup(pnlFeltetekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSajt)
                    .addComponent(spnSajt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFeltetekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxJapanejo)
                    .addComponent(spnJalapenjo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFeltetekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAnanasz)
                    .addComponent(spnAnanasz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFeltetekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSzalami)
                    .addComponent(spnSzalami, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlMeret.setBorder(javax.swing.BorderFactory.createTitledBorder("Méret(cm)"));

        cmbMeret.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "25", "30", "45", "50" }));

        javax.swing.GroupLayout pnlMeretLayout = new javax.swing.GroupLayout(pnlMeret);
        pnlMeret.setLayout(pnlMeretLayout);
        pnlMeretLayout.setHorizontalGroup(
            pnlMeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeretLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbMeret, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMeretLayout.setVerticalGroup(
            pnlMeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeretLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        btnRendeles.setBackground(new java.awt.Color(153, 153, 0));
        btnRendeles.setText("Rendelés");
        btnRendeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendelesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRendeles)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlPizzafelek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pnlFeltetek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlMeret, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPizzafelek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFeltetek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRendeles)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSajtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSajtItemStateChanged
    if (evt.getStateChange() == ItemEvent.SELECTED) {
        spnSajt.setEnabled(true);
    } else {
        spnSajt.setEnabled(false);
    }
    }//GEN-LAST:event_cbxSajtItemStateChanged

    private void cbxJapanejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxJapanejoActionPerformed

    }//GEN-LAST:event_cbxJapanejoActionPerformed

    private void cbxJapanejoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxJapanejoItemStateChanged
    if (evt.getStateChange() == ItemEvent.SELECTED) {
        spnJalapenjo.setEnabled(true);
    } else {
        spnJalapenjo.setEnabled(false);
    }
    }//GEN-LAST:event_cbxJapanejoItemStateChanged

    private void cbxAnanaszItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAnanaszItemStateChanged
    if (evt.getStateChange() == ItemEvent.SELECTED) {
        spnAnanasz.setEnabled(true);
    } else {
        spnAnanasz.setEnabled(false);
    }
    }//GEN-LAST:event_cbxAnanaszItemStateChanged

    private void cbxSzalamiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSzalamiItemStateChanged
    if (evt.getStateChange() == ItemEvent.SELECTED) {
        spnSzalami.setEnabled(true);
    } else {
        spnSzalami.setEnabled(false);
    }
    }//GEN-LAST:event_cbxSzalamiItemStateChanged

    private void btnRendelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRendelesActionPerformed
    boolean vanPizzaValasztva = cmbPizzafelek.getSelectedIndex() > 0;
    String uzenet;
    String meret;
    if (vanPizzaValasztva) {
        uzenet = cmbPizzafelek.getSelectedItem().toString();
        meret = cmbMeret.getSelectedItem().toString();
        JOptionPane.showMessageDialog(rootPane, "A rendelés kész!\n"+uzenet+"\n"+ meret+ " cm" + "\n1500 ft", "Rendelés", 1);
        System.exit(0);
    } else {
        uzenet = "Nincs pizza választva";
        JOptionPane.showMessageDialog(rootPane, uzenet, "Rendelés", 0);
    }
    }//GEN-LAST:event_btnRendelesActionPerformed

    private void cmbPizzafelekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPizzafelekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPizzafelekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pizzaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pizzaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pizzaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pizzaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pizzaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRendeles;
    private javax.swing.JCheckBox cbxAnanasz;
    private javax.swing.JCheckBox cbxJapanejo;
    private javax.swing.JCheckBox cbxSajt;
    private javax.swing.JCheckBox cbxSzalami;
    private javax.swing.JComboBox<String> cmbMeret;
    private javax.swing.JComboBox<String> cmbPizzafelek;
    private javax.swing.JLabel lblPizza;
    private javax.swing.JPanel pnlFeltetek;
    private javax.swing.JPanel pnlMeret;
    private javax.swing.JPanel pnlPizzafelek;
    private javax.swing.ButtonGroup rdbgPizzafelek;
    private javax.swing.JSpinner spnAnanasz;
    private javax.swing.JSpinner spnJalapenjo;
    private javax.swing.JSpinner spnSajt;
    private javax.swing.JSpinner spnSzalami;
    // End of variables declaration//GEN-END:variables
}
